version: '2.1'

services:
    rt1:
        image: snisioi/cap2:latest
        volumes:
            - .:/elocal
        tty: true
        ports:
            - 10000:10000/udp
    rt2:
        image: snisioi/cap2:latest
        volumes:
            - .:/elocal
        tty: true
